development:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: inventory7d_dev
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: localhost
  username: root
  password:  
  database: inventory7d_test
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: inventory7d
  encoding: utf8
  pool: 5
  timeout: 5000
